"""BLASST sparse FlashAttention integration for LLaDA."""

from .flash_attention import (
    ActiveVoterStats,
    BlasstStats,
    blasst_flash_attn_func,
    collect_active_voter_stats,
    collect_blasst_stats,
    install_blasst,
)
from .calibration import (
    PhysicalCalibrationRegression,
    PhysicalTileScoreCollector,
    calibration_matches_runtime_defaults,
    lambda_for_physical_sparsity,
    load_physical_calibration,
    select_largest_eligible_lambda,
)
from .triton_bidirectional import (
    DiffusionKernelController,
    DiffusionLambdaSchedule,
    KernelStats,
    blasst_bidirectional_flash_attn_func,
    get_kernel_stats,
    install_bidirectional_blasst_kernel,
    install_diffusion_blasst_kernel,
    reset_kernel_stats,
)
from .pre_qk import (
    PreQKKernelConfig,
    PreQKKernelController,
    PreQKMetadataBuffers,
    install_pre_qk_blasst_kernel,
)
from .runtime import (
    DenoisingMetadataStore,
    PreviousStepMetadata,
    ReferenceResult,
    ReferenceStructuralStats,
    StructuralOptimizationConfig,
    aggregate_step_metadata,
    build_kv_priority_order,
    build_query_permutation,
    structural_blasst_reference,
)
from .regrouping import (
    RegroupingMetrics,
    aggregate_heads,
    build_head_group_permutations,
    build_permutation,
    build_windowed_permutation,
    evaluate_permutation,
    mean_jaccard,
    pack_keep_mask,
    unpack_keep_mask,
)
from .exception_packing import (
    PackabilityMetrics,
    active_counts,
    exception_tiles_per_row_histogram,
    grouped_exception_totals,
    summarize_packability,
)
from .veto_pruning import (
    CumulativeBudgetPolicy,
    KVetoPolicy,
    ScoreThresholdPolicy as VetoScoreThresholdPolicy,
    VetoPolicyStats,
)
from .tile_reuse import (
    AttentionTileStatistics,
    TileCacheFootprint,
    attention_tile_statistics,
    compose_attention_tile_statistics,
    merge_attention_tile_statistics,
    query_tile_output_cache_footprint,
    tiled_attention_reference,
    two_dimensional_cache_footprint,
)
from .certified_omission import (
    LogNormalizerInterval,
    advance_log_normalizer_interval,
    attention_output_after_omission,
    certified_tile_mass_upper,
    greedy_mass_budget_omission,
    refresh_log_normalizer_interval,
    temporal_score_perturbation_bound,
)

__all__ = [
    "BlasstStats",
    "ActiveVoterStats",
    "CumulativeBudgetPolicy",
    "DiffusionKernelController",
    "DiffusionLambdaSchedule",
    "KernelStats",
    "KVetoPolicy",
    "PackabilityMetrics",
    "PreQKKernelConfig",
    "PreQKKernelController",
    "PreQKMetadataBuffers",
    "DenoisingMetadataStore",
    "PreviousStepMetadata",
    "ReferenceResult",
    "ReferenceStructuralStats",
    "RegroupingMetrics",
    "StructuralOptimizationConfig",
    "VetoPolicyStats",
    "VetoScoreThresholdPolicy",
    "AttentionTileStatistics",
    "TileCacheFootprint",
    "PhysicalTileScoreCollector",
    "PhysicalCalibrationRegression",
    "calibration_matches_runtime_defaults",
    "blasst_flash_attn_func",
    "blasst_bidirectional_flash_attn_func",
    "attention_tile_statistics",
    "aggregate_step_metadata",
    "aggregate_heads",
    "active_counts",
    "build_kv_priority_order",
    "build_query_permutation",
    "build_head_group_permutations",
    "build_permutation",
    "build_windowed_permutation",
    "collect_blasst_stats",
    "collect_active_voter_stats",
    "compose_attention_tile_statistics",
    "get_kernel_stats",
    "evaluate_permutation",
    "exception_tiles_per_row_histogram",
    "grouped_exception_totals",
    "install_blasst",
    "install_bidirectional_blasst_kernel",
    "install_diffusion_blasst_kernel",
    "install_pre_qk_blasst_kernel",
    "lambda_for_physical_sparsity",
    "mean_jaccard",
    "merge_attention_tile_statistics",
    "pack_keep_mask",
    "load_physical_calibration",
    "select_largest_eligible_lambda",
    "structural_blasst_reference",
    "summarize_packability",
    "unpack_keep_mask",
    "reset_kernel_stats",
    "query_tile_output_cache_footprint",
    "tiled_attention_reference",
    "two_dimensional_cache_footprint",
    "LogNormalizerInterval",
    "advance_log_normalizer_interval",
    "attention_output_after_omission",
    "certified_tile_mass_upper",
    "greedy_mass_budget_omission",
    "refresh_log_normalizer_interval",
    "temporal_score_perturbation_bound",
]
