"""CPU-only receipts for the *existing* vLLM JIT monitor.

Usage after vLLM has installed/activated its monitor::

    with jit_receipts(monitor) as receipts:
        # Complete the panel's own warm requests first.
        before = receipts.snapshot()
        run_timed_request()
        after = receipts.snapshot()

Subtract corresponding integer counts at request boundaries. This helper adds
no CUDA operations, synchronization, device-library imports, logging, or
per-kernel-hit hooks.
It counts monitor entry events before logging deduplication and before a monitor
error is raised. A Triton event is a runtime cache-miss finalization, possibly
loading an on-disk artifact; a CuTe event is a monitored cute.compile invocation,
possibly cached or unsuccessful. Neither is a count of new machine-code builds.

Coverage is limited to calls reaching the installed _handle_jit_event. The
helper does not activate the monitor or establish that its hooks cover every
compiler/previously captured CuTe alias. It does not count autotuning, pending
async compile submissions, CUDA graphs, backend/Inductor compilation, or work
in other worker processes. Zero here alone does not prove absence of all JIT.
Install once per measured worker; contexts on one monitor must be nested in
LIFO order and must not overlap independent patchers.

Only aggregate integers are retained: function names, signatures, details and
source/kernel identifiers are passed through without being stored in receipts.
"""
from __future__ import annotations

from contextlib import contextmanager
from functools import wraps
import inspect
import sys
from threading import Lock


COUNT_FIELDS = ('triton_events', 'cute_events', 'unknown_events', 'all_events')
_KNOWN_EVENTS = {
    ('Triton', 'kernel JIT compilation'): 'triton_events',
    ('CuTeDSL', 'JIT compilation'): 'cute_events',
}


class JitReceipts:
    """Thread-safe host counters; snapshots are independent public dictionaries."""

    def __init__(self):
        self._counts = dict.fromkeys(COUNT_FIELDS, 0)
        self._lock = Lock()

    def _record(self, backend, event):
        # Exact strings are the installed monitor's public event parameter
        # types. Do not coerce unknown objects (or expose their repr/details).
        field = (_KNOWN_EVENTS.get((backend, event), 'unknown_events')
                 if type(backend) is str and type(event) is str
                 else 'unknown_events')
        with self._lock:
            self._counts[field] += 1
            self._counts['all_events'] += 1

    def snapshot(self):
        """Return cumulative counts, with no device reads or synchronization."""
        with self._lock:
            return self._counts.copy()


@contextmanager
def jit_receipts(monitor=None):
    """Temporarily wrap an existing monitor and restore its exact handler.

    Pass the worker's jit_monitor module explicitly, or omit it only when that
    module is already in sys.modules. The monitor's signature, return values,
    warnings and exceptions remain authoritative. Invalid argument calls are
    delegated unchanged and are not counted as JIT events.
    """
    if monitor is None:
        monitor = sys.modules.get('vllm.utils.jit_monitor')
    original = getattr(monitor, '_handle_jit_event', None)
    if not callable(original):
        raise RuntimeError('an existing vLLM jit_monitor handler is required')
    signature = inspect.signature(original)
    if not {'backend', 'event'}.issubset(signature.parameters):
        raise RuntimeError('unsupported jit_monitor event signature')
    receipts = JitReceipts()

    @wraps(original)
    def counted(*args, **kwargs):
        try:
            bound = signature.bind(*args, **kwargs)
        except TypeError:
            # Preserve the original call error and its behavior, not the error
            # generated by inspect.Signature.bind.
            return original(*args, **kwargs)
        bound.apply_defaults()
        receipts._record(bound.arguments['backend'], bound.arguments['event'])
        return original(*args, **kwargs)

    monitor._handle_jit_event = counted
    try:
        yield receipts
    finally:
        monitor._handle_jit_event = original
